### ISSUE TITLE
Possible time zone problem

### ISSUE THREAD

**Issue by rwb196884** [thomasgalliker/NCrontab.Scheduler#21]
I have a job with schedule
```
34 16 * * *
```
and it's actually running at 17:34 local time. Local time is currently UTC+0100.

**Comment by thomasgalliker** [comment]
Ok. I will have a look at it.

**Comment by thomasgalliker** [comment]
Yeah, I analyzed this issue and came to the conclusion that it works as expected. (Please let me know if this is wrong in your eyes). The scheduler operates with UTC times for good reasons. I'm not sure if/how we could solve this issue. Maybe we could configure the scheduler to run with local time instead of UTC but I guess we would run into troubles (missing events during daylight saving time changes, etc).

**Comment by rwb196884** [comment]
On a *nix system `cron` expressions are evaluated in system time, therefore evaluating them using UTC is unexpected behaviour.

Therefore I'd recommend making it **much** clearer in the documentation and XML/intellisense comments that all `cron` expressions are evaluated in UTC.

**Comment by thomasgalliker** [comment]
Cron expressions are always in UTC, that's true. Scheduler operations should also run with UTC, always. I can add some comments. However, the CronExpression classes are not part of this library - they come from NCrontab (which is another library).

**Comment by rwb196884** [comment]
It looks to me like `NCrontab` uses whatever it's given -- if you pass it local times then it generates local times and if you pass it UTC then it generates UTC.
```
            DateTime tL = DateTime.Now; // local/London
            DateTime tU = DateTime.UtcNow; // UTC
            CrontabSchedule schedule = CrontabSchedule.Parse("5 16 * * *"); // 16:05 every day.
            List<DateTime> oL = schedule.GetNextOccurrences(tL, tL.AddDays(14)).ToList(); // 16:05 local.
            List<DateTime> oU = schedule.GetNextOccurrences(tU, tU.AddDays(14)).ToList(); // 16:05 utc.
```

I can follow your code through as far as `scheduler.AddTask(taskId, crontabSchedule, action);` on line 37 of `SchedulerExtension` but I can't find any method called `AddTask` that takes a `Guid` as its first parameter.

Gut feeling is that somehwere inside there you have to pick a start time in order to enumerate the occurrences of the schedule and this is where UTC is being selected in preference to local/machine time.

**Comment by thomasgalliker** [comment]
You are right. When I calculate the next scheduling date, I pass DateTime.UtcNow as a reference date. In #22 I extended the code with a new SchedulerOptions class, which has a property "DateTimeKind". If you set it to "Local" (default is Utc), it will calculate the execution dates based on local time.

I would be very happy if you could check the code in #22 and see if I made some mistakes. 
- I'm not sure if the code works across daylight saving days
- I'm also not sure if the signal time really has to be a local time or if it can remain UTC

**Comment by rwb196884** [comment]
Looks perfectly sensible :)

But I can't find a way to set the settings.  (I'm using the extension method `AddScheduler` to register `IScheduler` with the DI container.)

**Comment by thomasgalliker** [comment]
I gonna add the options to the AddScheduler method 👌🏻

**Comment by thomasgalliker** [comment]
@rwb196884 can you try the latest nuget pre-release of [NCrontab.Scheduler](https://www.nuget.org/packages/NCrontab.Scheduler/1.2.1-pre) and let me know if this fits to you.

**Comment by rwb196884** [comment]
Found version `1.2.1-pre`

Default behaviour appears still to be UTC.

New overload for registering the service used as
```
                    services.AddScheduler(configureOptions =>
                    {
                        configureOptions.DateTimeKind = DateTimeKind.Local;
                    });
```
switches it to local.

In the log messages the time is still UTC; the format is something like `yyyy-MM-ddTHH:MM:ss.ffff` (give or take a few `f`s) and a `zzz` might be helpful to eliminate any possible ambiguity.

**Comment by thomasgalliker** [comment]
I would like to keep the default DateTimeKind.Utc because this is the default on linux systems afaik.

The log messages I left UTC intentionally. Logging is a very technical activity and always recommended to be in UTC. Otherwise it can get very weird during daylight saving time changes.
There should be a “Z” in the timestamp indicating it is UTC formatted. I will check that again.

**Comment by rwb196884** [comment]
Looks perfectly sensible :)

But I can't find a way to set the settings.  (I'm using the extension method `AddScheduler` to register `IScheduler` with the DI container.)

**Comment by rwb196884** [comment]
Good work :)
Just double check that documentation and XML comments are in place so that idiots like me know when to expcect UTC.

**Comment by thomasgalliker** [comment]
Thanks @rwb196884 for reporting and for your help. I think I will update readme.md as well as the in-code documentation with better information in this regard. If something else is changed, I'll let you know in this issue. It will take some more days until I can merge it.
